MUI-424 Forcing signature in reservations created by Admin
ABRGI/nelson-test-automation pull request #13
Opened 2023-05-15 11:33 UTC by lngtrn

2023-05-16 00:34 UTC, softico-sara requested changes
See comments for change requests: at least secrets must be removed and Waits handled differently. Otherwise very good job, you got the hang of it very quickly!

2023-05-16 00:34 UTC, softico-sara commented on resources/keywords/mui.resource
Remove any real emails and credentials! this is a public repo and everything is on the internet!

2023-05-16 00:34 UTC, softico-sara commented on .github/workflows/python-app.yml
tests are to be run headless (i had it wrong in in the yml) - do we need to have X/displays there or did you have a reason for that?

2023-05-16 00:34 UTC, softico-sara commented on resources/keywords/booking.resource
For Fill in Payments details, you could also create an IF statement that contains all things if env is bui/mui instead of using the keyword Run keyword If multiple times. Or even have two separate keywords that are to be run depending on the env. This is fine now, but if you want to do refactoring at some point, this could be a smarter way.

2023-05-16 00:34 UTC, softico-sara commented on .github/workflows/python-app.yml
for now, we can run the test suites separately, but  for the AWS pipeline we will implement parallel running in order to save time to run (nothing needed for you to be done at this point)

2023-05-16 00:34 UTC, softico-sara commented on resources/keywords/mui.resource
Even though Wait keywords exist in Robot, they are encouraged to be used wisely and rarely. I added a section to our Confluence page to explain this: [here](https://projectnelson.atlassian.net/wiki/spaces/NELS/pages/2261155841/Robot+Framework+Practices+for+QA#Why-Waits-aren%E2%80%99t-encouraged)

So any Waits with seconds should only be used for debugging purposes! Instead use Wait keywords that are not explicit ie Wait for element state etc. This is important to be done right from the start!

2023-05-16 00:34 UTC, softico-sara commented on testsuites/examples.robot
While what you did here is generally good, I advise not to do "general" changes whenever you are working on a specific issue. So try to keep any changes in a branch related to said issue ie. MUI-424. General refactorings can then be done in a separate issue.

This will also reduce the amount of merge requests when several people are working with the repository.

2023-05-16 06:48 UTC, lngtrn commented on .github/workflows/python-app.yml
no, for now, we can run tests in CI without display

2023-05-17 00:43 UTC, softico-sara approved these changes
Good work, I will give you more feedback after I have merged this to develop - let's use that as our working branch and keep "master" clean.

2023-05-17 00:46 UTC, softico-sara commented
Since I have done a lot of changes yesterday to booking, common and yml, there are now a lot of conflicts. I will resolve them for this merge request but for the next one prepare to do it on your own, it's fun :D haha no...

After this is done and you feel your task is completed, fetch/pull develop and start with a new issue and branch!

2023-05-17 01:10 UTC, merged